flowchart LR
  subgraph lane_0["Planning"]
    t_0{"啊是假的快乐就阿斯利康大姐卡拉斯京大叔科技大厦的"}
    t_1(["Start"])
    t_2["Define Requirements撒大姐卡是假的看辣椒素的快乐就撒到了啊是大姐"]
  end
  subgraph lane_1["Development"]
    t_3["Implement Feature"]
  end
  subgraph lane_2["Review"]
    t_4["Process 3"]
    t_5{"Decision 2"}
    t_6["Code Review"]
  end
  t_1 --> t_2
  t_2 --> t_0
  t_0 -->|"Yes"| t_3
  t_3 --> t_6
