mindmap  物流相关需求整理 导入公里数和费用 需求连接：https://souche.yuque.com/gp0gfa/lg26bb/erly0gkfgrhpnphy 简介：在导入公里数菜单中增加导入公里数和费用功能；导入字段分为：订单号、公里数、费用，三项均必填，导入后系统将按照订单号查询对应的订单，然后更新订单上的公里数和费用 业务场景：适用于大客户订单经常修改订单公里数和费用 运力调度询价、订单展示订单跟进信息 需求连接：https://souche.yuque.com/gp0gfa/lg26bb/adflagyf3aqofbsf 简介：在运力调度的询价、订单展示客服在订单上设置的跟进信息（散户和大客户跟进信息结构不同，对应的订单需要取对应的跟进信息） New node Topic 3 New node New node