flowchart LR
  subgraph lane_0["Lane 1"]
    t_0["Process 2"]
    t_1{"判断 3"}
    t_2(["Start / End 2"])
  end
  subgraph lane_1["Lane 2"]
    t_3["流程 4"]
    t_4{"判断 3"}
    t_5{"Decision 2"}
    %% [tag:pending] 待确认 | 阿斯顿撒娇看了大姐撒开
    t_6["Process 1"]
  end
  subgraph lane_2["Lane 3"]
    t_7["流程 2"]
    t_8["Process 1<br/>asdasjkd"]
    %% [tag:other] 其他 | 2为企鹅12312321
  end
  t_2 --> t_0
  t_0 --> t_6
  t_6 --> t_5
  t_6 --> t_8
  t_7 --> t_4
  t_5 --> t_4
  t_3 --> t_5
