flowchart LR
  subgraph lane_0["用户"]
    t_0(["录入托运信息"])
    t_1{"是否确认运输"}
    t_2{"用户是否支付成功"}
    t_3["不处理"]
    t_4["等待支付"]
    t_5{"用户是否支付"}
    t_6["不处理"]
  end
  subgraph lane_1["支付宝"]
    t_7["提交订单信息"]
    t_8["展示价格信息"]
    t_9["记录托运信息"]
    t_10["展示支付成功"]
    t_11["展示待⽀付账单"]
    t_12["接收通知"]
    t_13["接收通知"]
    t_14["拉起收银台"]
    t_15["展示支付成功"]
  end
  subgraph lane_2["交付系统"]
    t_16[/"使用订单的预付款金额调用支付宝js API创建交易单，生成交易单号<br/>订单状态=待支付"\]
    t_17[/"客服需要查询支付宝订单，与客户沟通确认运车细节后，才能进入运力竞价"\]
    %% [tag:other] 其他 | 这里需要给客服培训，使用特定流程处理支付宝渠道的订单
    t_18[/"在取价规则和加价规则中为支付宝配置渠道值和规则"\]
    %% [tag:existing] 已有 | 需要配置支付宝聚合搜索渠道，配置相关取价规则和加价规则，应该不涉及到代码修改，只需要配置即可
    t_19[/"记录查价记录"\]
    t_20[/"available：true，price_type：MEMBER，transport_type：LARGE_TRUCK，price_info:{}"\]
    t_21{"是否支付成功"}
    t_22{"是否支付成功"}
    t_23{"金额是否有变化"}
    t_24["【销售】补充车架号、车辆品牌信息，修改订单金额（若金额不正确）"]
    t_25{"汽车还是摩托车"}
    t_26["查询支付状态"]
    %% [tag:new] 新增 | 新增的支付状态查询逻辑
    t_27["订单状态=待竞价"]
    t_28["【销售】查看支付宝渠道订单"]
    t_29["【司机、售后】上传交车单，交车"]
    t_30["调用⽀付单状态同步接口"]
    %% [tag:new] 新增 | 新增接口推送逻辑
    t_31["查询订单支付状态"]
    %% [tag:new] 新增 | 新增逻辑
    t_32["【运力】确认竞价"]
    t_33["【销售】人工通知运力可以竞价"]
    t_34{"是否有线路（大板、小板）价格"}
    t_35["【售后】派单"]
    t_36["【司机、售后】确认提车"]
    t_37["【司机、售后】到达交车地"]
    t_38["【司机、售后】发运"]
    t_39["下单"]
    %% [tag:new] 新增 | 与原有的下单接口可能不同，需要新增
    t_40["创建支付宝支付单号"]
    %% [tag:new] 新增 | 支付宝订单需要自动调用支付宝接口，生成交易单号
    t_41["关联查价单号，更新订单报价"]
    %% [tag:new] 新增 | 需要关联订单号
    t_42["自动确认报价"]
    %% [tag:new] 新增 | 支付宝渠道过来的订单需要自动确认报价
    t_43["查询大板线路库"]
    %% [tag:existing] 已有 | 在查价的时候，需要增加会员检查和自动注册逻辑
    t_44["推送价格"]
    %% [tag:new] 新增 | 新增的推送价格接口
    t_45["干线+保障服务费"]
    t_46["调用汽车托运订单状态同步同步订单状态=服务完成（CS_ARRIVED）"]
    %% [tag:new] 新增 | 新增接口推送逻辑
    t_47["兜底计算规则，返回价格信息"]
    %% [tag:pending] 待确认 | 是否需要兜底计算规则，还是直接返回不能承运
    t_48["调用汽车托运订单状态同步同步订单状态=运送中（CS_DELIVERING）"]
    %% [tag:new] 新增 | 新增接口推送逻辑
    t_49["调用汽车托运订单状态同步接口同步订单状态=待接单<br/>（CS_TO_PICK_UP）"]
    %% [tag:new] 新增 | 新增逻辑
    t_50["调用汽车托运订单状态同步同步订单状态=已接单（CS_TAKE_ORDER）"]
    %% [tag:new] 新增 | 新增接口推送逻辑
    t_51["调用汽车托运订单状态同步同步订单状态=已取车（CS_PICKED_UP）"]
    %% [tag:new] 新增 | 新增接口推送逻辑
    t_52["返回不可承运available=false"]
    t_53["使用支付单状态同步接口更新订单金额和支付状态"]
    %% [tag:new] 新增 | 新增逻辑
    t_54[/"缺失信息使用默认值补充，比如车型车系等，后续需要人工确认并修改"\]
    t_55{"查询次数是否超过3次"}
    t_56[/"订单号关联查价单号，查价单号在下单时支付宝会传过来"\]
    t_57["调用汽车托运订单状态同步同步订单状态=订单完成（CS_SUCCESS）"]
    %% [tag:new] 新增 | 新增接口状态同步逻辑
    t_58["调用支付状态同步接口，更新状态为：待支付"]
    t_59{"creator_phone是否已注册"}
    t_60["使用creator_phone注册会员"]
    %% [tag:new] 新增 | 在查价的时候就需要注册会员
    t_61[/"此处跳过了订单状态=已送达（CS_ARRIVED），因为需要推送账单给客户"\]
    t_62["调用支付状态同步接口，"]
    t_63[/"同步：待⽀付 (TO_PAY)，明细 (order_fee, base_delivery_fee 等)"\]
    t_64["流程 62"]
    t_65[/"此时无法交车"\]
    t_66["等待10秒继续查询"]
    t_67{"查询是否超过3次"}
    t_68["调用支付状态同步接口，更新状态为：待支付"]
    t_69["不处理，无需自动注册"]
    t_70[/"当前支付宝支付状态缺少待支付定金还是待支付尾款，无法区分用户应当支付哪一笔"\]
    t_71["等待10秒后再次查询"]
    t_72["调用支付状态同步接口，更新状态为：支付完成"]
    t_73["用户在其他渠道支付完成"]
    t_74["调用支付状态同步接口，更新状态为：支付完成"]
    t_75["用户在其他渠道支付完成"]
    t_76[/"不允许使用微信在线支付"\]
    t_77[/"不允许使用微信在线支付"\]
  end
  t_0 --> t_9
  t_9 --> t_25
  t_25 -->|"摩托车"| t_52
  t_25 -->|"汽车"| t_43
  t_43 --> t_34
  t_34 -->|"是"| t_45
  t_43 --> t_59
  t_59 -->|"否"| t_60
  t_18 -.-> t_43
  t_34 -->|"否"| t_47
  t_47 --> t_45
  t_8 --> t_1
  t_1 -->|"否"| t_3
  t_1 -->|"是"| t_7
  t_7 -->|"调用下单接口"| t_39
  t_39 --> t_41
  t_56 -.-> t_41
  t_41 --> t_42
  t_42 --> t_40
  t_40 -->|"返回订单信息和支付信息"| t_14
  t_5 -->|"否"| t_6
  t_14 --> t_5
  t_5 --> t_15
  t_15 -->|"通知支付成功"| t_31
  t_31 --> t_21
  t_21 -->|"否"| t_67
  t_67 -->|"否"| t_71
  t_71 --> t_31
  t_67 -->|"是"| t_68
  t_70 -.-> t_68
  t_21 -->|"是"| t_27
  t_17 -.-> t_27
  t_27 --> t_28
  t_28 --> t_24
  t_24 --> t_23
  t_23 -->|"是"| t_53
  t_23 -->|"否"| t_33
  t_53 --> t_33
  t_33 --> t_32
  t_32 --> t_35
  t_32 --> t_50
  t_27 --> t_49
  t_16 -.-> t_40
  t_35 --> t_36
  t_36 --> t_51
  t_36 --> t_38
  t_38 --> t_48
  t_38 --> t_37
  t_37 --> t_46
  t_61 -.-> t_46
  t_29 --> t_57
  t_11 --> t_2
  t_2 -->|"否"| t_4
  t_2 --> t_10
  t_10 -->|"推送支付状态"| t_26
  t_22 -->|"否"| t_55
  t_26 --> t_22
  t_55 -->|"否"| t_66
  t_66 --> t_26
  t_22 -->|"是"| t_29
  t_55 -->|"是"| t_58
  t_65 -.-> t_58
  t_37 --> t_30
  t_30 --> t_11
  t_59 -->|"是"| t_69
  t_45 --> t_44
  t_44 --> t_8
  t_20 -.-> t_44
  t_30 --> t_63
  t_54 -.-> t_39
  t_19 -.-> t_43
  t_29 -->|"返回result=true"| t_12
  t_27 -->|"返回result=true"| t_13
  t_40 -.-> t_75
  t_75 -->|"alipay_trade_no为空"| t_74
  t_73 -->|"alipay_trade_no为空"| t_72
  t_37 -.-> t_73
  t_76 -.-> t_73
  t_77 -.-> t_75
