flowchart TD
  n_0(["查询报价"])
  n_1{"渠道是否有报价规则"}
  n_2("不自动报价")
  n_3{"是否设置大板取价规则"}
  n_4{"是否设置小板取价规则"}
  n_5{"是否有直运线路"}
  n_6{"是否开启中转线路"}
  n_7{"是否开启中转线路"}
  n_8("查询中转线路")
  n_9("使用直运干线价格")
  n_10("查询中转线路")
  n_11{"是否有中转线路"}
  n_12("使用中转线路报价")
  n_13{"是否有中转线路"}
  n_14("直运和中转对比，进行取价")
  n_15[/"订单来源=支付宝聚合搜索时，需要给支付宝返回不可承运"\]
  n_16("查询小板线路")
  n_17{"是否开启线路取价"}
  n_18{"是否开启大板兜底取价"}
  n_19("查询大板兜底规则")
  n_20{"是否命中兜底规则"}
  n_21("使用兜底价格")
  n_22{"是否开启线路取价"}
  n_23{"是否有直运线路"}
  n_24("使用小板线路价格")
  n_25("查询小板兜底规则")
  n_26{"是否开启兜底取价"}
  n_27{"是否开启兜底取价"}
  n_28("不返回报价")
  n_29{"是否开启小板兜底取价"}
  n_30{"是否命中兜底规则"}
  n_31("使用小板兜底报价")
  n_32("不返回小板报价")
  n_33("不返回小板报价")
  n_34("不返回报价")
  n_35("价格汇总")
  n_0 --> n_1
  n_1 -->|"否"| n_2
  n_1 -->|"是"| n_3
  n_3 -->|"否"| n_4
  n_5 -->|"否"| n_6
  n_5 -->|"是"| n_7
  n_7 -->|"是"| n_8
  n_6 -->|"是"| n_10
  n_10 --> n_11
  n_8 --> n_13
  n_13 -->|"是"| n_14
  n_2 -.-> n_15
  n_3 -->|"是"| n_17
  n_17 -->|"是"| n_5
  n_17 -->|"否"| n_18
  n_18 -->|"是"| n_19
  n_19 --> n_20
  n_20 -->|"是"| n_21
  n_4 -->|"是"| n_22
  n_22 -->|"是"| n_16
  n_16 --> n_23
  n_23 -->|"是"| n_24
  n_13 --x|"否"| n_9
  n_7 -->|"否"| n_9
  n_6 -->|"否"| n_26
  n_26 -->|"是"| n_19
  n_11 -->|"否"| n_27
  n_11 -->|"是"| n_12
  n_27 -->|"是"| n_19
  n_22 -->|"否"| n_28
  n_28 -.-> n_15
  n_23 -->|"否"| n_29
  n_29 --> n_25
  n_25 --> n_30
  n_30 -->|"是"| n_31
  n_30 -->|"否"| n_32
  n_32 --> n_32
  n_29 -->|"否"| n_33
  n_4 -->|"否"| n_34
  n_34 -.-> n_15
  n_18 -->|"否"| n_4
  n_20 -->|"否"| n_4
  n_26 -->|"否"| n_4
  n_27 -->|"否"| n_4
