flowchart LR
  subgraph lane_0["客户"]
    t_0{"是否确认取消"}
    t_1(["发起取消订单"])
    t_2["不处理"]
    t_3["Process 4"]
  end
  subgraph lane_1["支付宝"]
    t_4["调用取消订单接口"]
    t_5["展示取消结果"]
    t_6["弹出取消确认弹窗"]
    t_7["预取消订单查询"]
    t_8["取消失败"]
    t_9["推送：退款通知"]
  end
  subgraph lane_2["交付系统"]
    t_10[/"订单无责任取消：allow_cancel = true，cancel_fee=null，pay_cancel_fee=null，is_free_cancel=true"\]
    t_11[/"allow_cancel = false，cancel_fee=null，pay_cancel_fee=null"\]
    t_12[/"cancel_status=success"\]
    t_13["【售后】人工提交退款申请"]
    t_14["【售后】线下接到退款申请"]
    t_15["【财务】支付宝商户后台手动退款"]
    t_16["【售后】退款凭证上传"]
    %% [tag:existing] 已有 | 已有功能改造
    t_17["调用支付单状态同步接口，通知退款"]
    %% [tag:new] 新增 | 新增接口推送
    t_18["返回取消成功"]
    t_19["取消订单、取消支付单"]
    t_20[/"order_status=REFUND<br/>含refund_fee, refund_desc"\]
    t_21[/"售后在线下收到退款申请，比如客服电话等，与客户核实运车信息"\]
    t_22["返回可取消"]
    t_23["返回不可取消"]
    t_24{"状态=已取消"}
    t_25{"状态=待支付"}
    t_26["查询订单状态"]
    %% [tag:new] 新增 | 新增接口
    t_27{"状态=已取消"}
    t_28{"状态=待支付"}
    t_29["不允许取消"]
    t_30["查询订单状态"]
    %% [tag:new] 新增 | 新增取消接口
    t_31[/"cancel_status=FAIL，<br/>sub_code=NOT_CAN_CANCEL，<br/>sub_msg=因订单已派单原因，不能取消，请联系人工客服"\]
  end
  t_1 --> t_7
  t_7 --> t_26
  t_26 --> t_24
  t_24 -->|"否"| t_25
  t_24 -->|"是"| t_22
  t_25 --> t_22
  t_22 --> t_6
  t_6 --> t_0
  t_0 -->|"否"| t_2
  t_0 --> t_4
  t_4 --> t_30
  t_30 --> t_27
  t_27 -->|"否"| t_28
  t_18 --> t_5
  t_12 -.-> t_18
  t_14 --> t_13
  t_13 --> t_15
  t_15 --> t_16
  t_16 --> t_17
  t_17 --> t_9
  t_28 -->|"否"| t_29
  t_29 --> t_8
  t_31 -.-> t_29
  t_21 -.-> t_14
  t_20 -.-> t_17
  t_25 -->|"否"| t_23
  t_11 -.-> t_23
  t_10 -.-> t_22
  t_27 -->|"是"| t_19
  t_28 -->|"是"| t_19
  t_19 --> t_18
