# 体检





| 项目 | 值 |
| --- | --- |
| 年龄 | 5.5岁 |
| 性别 | 男 |
| 体重 | 19.44 |
| 身高 | 117.9 |
| 左眼视力 | 1.0 |
| 右眼视力 | 1.0 |
| 右眼球径 | +0.75 |
| 右眼柱径 | -1.25 |
| 右眼轴位 | 7 |
| 左眼球径 | +0.75 |
| 左眼柱径 | -1.00 |
| 左眼轴位 | 17 |
| 牙齿数 | 20 |
| 龋齿数 | 0 |
| 血红蛋白 | 111 |