sequenceDiagram
  autonumber
  actor p0 as 商户系统
  participant p1 as ⽀付宝平台
  actor p2 as 用户
  Note over p0,p1: ⽀付单状态同步
  Note over p0,p1: 到付/尾款场景
  p0->>p1: 同步：待支付（TO_PAY）含费用明细（order_fee,base_delivery_fee等）
  p1->>p2: 展示待⽀付账单
  p2-->>p1: 完成⽀付
  p1->>p0: ⽀付成功通知 (spi.alipay.commerce.logistics.carshipping.order.pay)
  p0-->>p1: 确认成功
  p0->>p1: 同步：⽀付成功 (PAY _ SUCCESS) 含抽佣⾦额 (commission _ fee)
  p1->>p2: 推 送：⽀付成功
  Note over p0,p1: 退款场景
  p0->>p1: 同步：退款 (REFUND) 含退款⾦额 (refund _ fee)、退款 因
  p1->>p2: 推 送：退款处理中
