sequenceDiagram
  autonumber
  actor p0 as 商户系统
  participant p1 as ⽀付宝平台
  actor p2 as ⽤ ⽤ 户
  p0->>p1: 状态同步接⼝ (alipay.commerce.logistics.waybill.status.sync)
  Note over p1: scene=CAR SHIPPING ORDER _data 包含订单状态信息 ALIPAY
  p1-->>p0: 同步成功
  Note over p0,p1,p2: 核⼼状态节点：
  Note over p0: CS_TO_PICKUP 待接单
  p0->>p1: 同步：已接单 (CS TAKE _ ORDER) 含司机姓名、电话、⻋架号
  p1->>p2: 推 送：司机已接单，正在赶往取⻋地
  p0->>p1: 同步：已取⻋ (CS PICKED _ _ 含⻋辆照⽚、VIN 码 UP)
  p1->>p2: 推 送：司机已接单，正在赶往取⻋地
  p0->>p1: 同步：运送 中 (CS _ DELIVERING)
  p1->>p2: 推 送：⻋辆在运输途中
  p0->>p1: 同步：已送达 (CS _ ARRIVED)
  p1->>p2: 推 送：⻋辆已送达⽬的地
  p0->>p1: 同步：服务完成 (CS SERVICE_COMPLETED)
  p1->>p2: 推 送：服务完成
  p0->>p1: 同步：订单完成 (CS _ SUCCESS)
  p1->>p2: 推 送：订单完成
